# This is a basic workflow to help you get started with Actions

name: CI
permissions:
  contents: write
# Controls when the workflow will run
on:
  # Triggers the workflow on push request for the "main" branch
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      # Runs node install and build
      - name: Run install
        run: npm install
      - name: Run Build
        run: npm run buildActions
        #404 page is loaded if the route is not matched this will redirect it to index.html again
      - name: Copy index as 404.html
        run: cp dist/index.html dist/404.html
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: pages